version: "3"

services:
  postgres:
    image: postgres:14.5-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./dumps:/code/dumps
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A app worker --loglevel=info -B
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./public:/code/public

  backend:
    build: .
    ports:
      - "8000:8000"
    restart: always
    entrypoint: /run.sh
    env_file:
      - .env
    volumes:
      - .:/backend
      - static_volume:/backend/static
    depends_on:
      - postgres

volumes:
  static_volume:
