version: "3"

services:
  postgres:
    image: postgres:14.5-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./dumps:/code/dumps
      - ./data/postgresql:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8000:8000"
    restart: always
    entrypoint: /run.sh
    env_file:
      - .env
    volumes:
      - .:/backend
      - static_volume:/backend/static
    depends_on:
      - postgres

volumes:
  static_volume:
