# Generated by Django 4.2.7 on 2023-11-13 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_alter_book_authors_alter_book_genres_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(default="", max_length=256, verbose_name="Слаг"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="book.book",
                verbose_name="Книги",
            ),
        ),
    ]
