# Generated by Django 4.2.7 on 2023-11-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_book_slug_alter_review_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=256, null=True, verbose_name="Слаг"
            ),
        ),
    ]
