# Generated by Django 4.2.7 on 2023-11-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_alter_book_authors_alter_book_genres_review"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="userfavorite",
            name="books",
            field=models.ManyToManyField(
                blank=True, to="book.book", verbose_name="Книги"
            ),
        ),
    ]
