# Generated by Django 4.2.7 on 2023-11-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_userfavorite_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="useremailconfirmmixin",
            name="is_confirmed",
            field=models.BooleanField(default=False, verbose_name="Почта подтвержден"),
            preserve_default=False,
        ),
    ]
