# Generated by Django 4.2.7 on 2023-11-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_useremailconfirmmixin_is_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useremailconfirmmixin",
            name="is_confirmed",
            field=models.BooleanField(default=0, verbose_name="Почта подтвержден"),
        ),
    ]
